# Generated by Django 5.0.6 on 2024-05-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetYasser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Jeu',
        ),
    ]
