# Generated by Django 5.0.6 on 2024-05-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetYasser', '0004_remove_jeu_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJoueur', models.CharField(max_length=100)),
                ('nomJeu', models.CharField(max_length=100)),
                ('nomEquipe', models.CharField(max_length=100)),
            ],
        ),
    ]
